version: 2
notify:
  webhooks:
    # A list of hashes representing hooks. Only the url field is supported.
    - url: https://api.reviewee.it/notification/ci
jobs:
  build:
    working_directory: ~/some-new-project
    docker:
      - image: cimg/node:14.18.0
      - image: postgres:latest
        environment:
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test
    environment:
      - REVIEWEE_URL: https://api.reviewee.it
      - COMMITS_CHECK_ENDPOINT: repository/growthval-api/haveRejectedCommits
      - COMMITS_CHECK_INDICATOR: \"success\":true
    steps:
      - run:
          name: Check rejected commits
          command: wget ${REVIEWEE_URL}/${COMMITS_CHECK_ENDPOINT} -q -O - | grep -q ${COMMITS_CHECK_INDICATOR}
      - checkout
      - run:
          name: Install System Dependencies
          command: sudo apt-get update -qq      
      - run: 
          name: Install Node dependencies
          command: npm install
      - run: 
          name: Check code quality
          command: npm run lint
      - run:
          command: npm run db:update
          environment:
            DATABASE_URL: postgres://admin:postgres@localhost:5432/test
            DATABASE_USE_SSL: 'false'    
      - run:
          name: Execute test cases
          command: npm run test
          environment:
            NODE_ENV: test
            DATABASE_USE_SSL: 'false'
            TEST_DATABASE_URL: postgres://admin:postgres@localhost:5432/test
            JWT_SECRET: 'SomeRandomTestSecret-512BitsAtLeast-eg.eyJhbGciOiJSUzI1NiJ9.bWVsb2dvOi8vaWRlbnRpdHkvdjEvMzI2MjY3NzMz'            
      - run:
         name: Deploy to Heroku
         command: git push --force https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_UAT_APP_NAME.git HEAD:refs/heads/master
  